---
#-------------------------------------------------------------------------------
# Install nginx
#-------------------------------------------------------------------------------
- name: install nginx repository
  yum: name="{{ item }}" state=present
  with_items:
    - "http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm"
  tags:
    - nginx

- name: update nginx repository file
  replace:
    dest: "/etc/yum.repos.d/nginx.repo"
    regexp: 'packages\/centos'
    replace: 'packages\/mainline\/centos'
    backup: yes
  tags:
    - nginx

- name: install nginx
  yum: name={{ item }} enablerepo=nginx state=present
  with_items:
    - nginx
  tags:
    - nginx

- name: put conf.d/default.conf
  template: src=nginx/default.conf.j2 dest=/etc/nginx/conf.d/default.conf backup=yes
  tags:
    - nginx

- name: put conf.d/virtual.conf
  template: src=nginx/virtual.conf.j2 dest=/etc/nginx/conf.d/virtual.conf backup=yes
  tags:
    - nginx

- name: set auto start nginx
  command: chkconfig nginx on
  tags:
    - nginx

#-------------------------------------------------------------------------------
# Install PHP-FPM
#-------------------------------------------------------------------------------
- name: install php-fpm
  yum: name={{ item }} state=present enablerepo=remi,remi-php56
  with_items:
    - php-fpm
  tags:
    - nginx

- name: put php-fpm.d/www.conf
  template: src=php-fpm/www.conf.j2 dest=/etc/php-fpm.d/www.conf backup=yes
  tags:
    - nginx

- name: start php-fpm
  command: /etc/init.d/php-fpm start
  tags:
    - nginx

- name: set auto start php-fpm
  command: chkconfig php-fpm on
  tags:
    - nginx

#-------------------------------------------------------------------------------
# Start nginx service
#-------------------------------------------------------------------------------
- name: port 80 process killed
  command: fuser -k 80/tcp
  ignore_errors: true
  tags:
    - nginx

- name: restart nginx
  service: name=nginx state=restarted
  tags:
    - nginx
