---

- stat: path=""

- name: Link storage/public to public/storage
  file:
    state: link
# TODO: ansistrano_shared_path は register されていないため、.stdoutを指定できない
# TODO:   src: "{{ ansistrano_shared_path.stdout }}{{ laravel_uploads_storage }}"
    src: "{{ ansistrano_shared_path }}{{ laravel_uploads_storage }}"
    path: "{{ ansistrano_release_path.stdout }}{{ laravel_uploads_public }}"
  when: laravel_uploads_storage != false